apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
spec:
  ttlSecondsAfterFinished: 86400
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: prchekuri/lms-db-migrator:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lms-db-migrate-url-secret
                  key: url
