apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: prchekuri/lms-prisma-migrate:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lms-db-migrate-url-secret
                  key: url
