apiVersion: v1
kind: Secret
metadata:
  name: lms-db-migrate-url-secret
type: Opaque
data:
  url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkMTIzQGxtcy1kYi1hd3MuY3RpcWVhODIwYTNtLnVzLXdlc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL3Bvc3RncmVzP3NzbG1vZGU9cmVxdWlyZQ==